# This is the project specific Settings.yml file.
# Place Sphinx specific build information here.
# Settings given here will replace the settings of 'conf.py'.

---
conf.py:
  copyright: 2007-2016
  project: Developer's Log
  version: 3.0
  release: 3.0.0
  latex_documents:
  - - Index
    - devlog.tex
    - Developer's Log
    - Francois Suter
    - manual
  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}
  intersphinx_mapping:
    t3tca:
    - http://docs.typo3.org/typo3cms/TCAReference/
    - null
    t3tsconfig:
    - http://docs.typo3.org/typo3cms/TSconfigReference/
    - null
    t3api:
    - http://docs.typo3.org/typo3cms/CoreApiReference/
    - null
  extensions:
  - sphinx.ext.intersphinx
  - t3sphinx.ext.t3extras
  - t3sphinx.ext.t3tablerows
  - t3sphinx.ext.targets
...
